### ISSUE TITLE
Error while trying to gather data

### ISSUE THREAD

**Issue by CJinTX** [marcincichocki/breach-protocol-autosolver#194]
**Describe the bug**

 Tried solving BP for the Killing the Name side job and it fails with Error While Trying to Gather Data

**To Reproduce**

Get to the Amusement Park terminal and try to hack it

**Expected behavior**

Should solve the BP like every other time

**Software information**

- Operating System: 
Edition	Windows 10 Home
Version	21H2
Installed on	‎1/‎2/‎2020
OS build	19044.1202
Experience	Windows Feature Experience Pack 120.2212.3920.0

- _Cyberpunk 2077_ platform: GOG PC
- _BPA_ version: 2.0.0-RC.0
- relevant _BPA_ settings:
![Fri Sep 03 2021 15 51 40 GMT-0500 (Central Daylight Time)](https://user-images.githubusercontent.com/90068828/132065196-ed673230-a87d-4baa-9832-89627cc116b4.png)
![2021-09-03 16_04_57-Window](https://user-images.githubusercontent.com/90068828/132065245-16b07cb2-450e-48b4-88ad-704a08f2d4e9.png)

**Additional files**

**Comment by marcincichocki** [comment]
Could you attach snapshot? I don't have save in that place to test it on my own.

**Comment by marcincichocki** [comment]
Bug fix will be deployed in the next version, thanks for reporting this issue!

**Comment by PweSol** [comment]
I'm using [2.10.0](https://github.com/marcincichocki/breach-protocol-autosolver/releases/tag/v2.10.0) and the issue still persist.

**Comment by marcincichocki** [comment]
Then it must be a different bug, daemon size of 6 is allowed. Please open another ticket.
