### ISSUE TITLE
Something wrong here I guess

### ISSUE THREAD

**Issue by playday3008** [marcincichocki/breach-protocol-autosolver#257]
![image](https://user-images.githubusercontent.com/18056374/159742263-2e1de420-5515-4224-b769-d0215a052912.png)

Why datamine_v1 unsolved?

**Comment by playday3008** [comment]
Really, wtf
![image](https://user-images.githubusercontent.com/18056374/159752869-cfa5cc06-81a1-4437-9063-eb412e3d04ac.png)

**Comment by playday3008** [comment]
![Wed Mar 23 2022 12 04 37 GMT+0100 (за центральноєвропейським стандартним часом)](https://user-images.githubusercontent.com/18056374/159752981-47c6aaae-494c-4247-a8af-e5e911075192.png)
Source image if someone want to test it

**Comment by marcincichocki** [comment]
I will buy you a beer if you find sequence that solves every deamon from screenshot you provided. Everything is working as expected, as there is no better solution.

**Comment by playday3008** [comment]
> I will buy you a beer if you find sequence that solves every deamon from screenshot you provided. Everything is working as expected, as there is no better solution.

Where is my beer?)

**Comment by marcincichocki** [comment]
New version [2.3.1](https://github.com/marcincichocki/breach-protocol-autosolver/releases/tag/v2.3.1) was released. Thanks for reporting this issue, and send me address you want you beer delivered to ;)
