### ISSUE TITLE
Add support for Ukrainian language

### ISSUE THREAD

**Issue by KolomakinA** [marcincichocki/breach-protocol-autosolver#371]
I am doing my walkthrough using the Ukrainian language, added in patch 2, and the app does not work for me at all

I'd like the app to support Ukrainian language

**Comment by marcincichocki** [comment]
First of all, game language option only allows to recognize daemon types. Lack of daemon type data will *not* stop autosolver from working completely, it will merely cause less optimized sequence order. If you have issues with running this program, please check [troubleshooting ](https://github.com/marcincichocki/breach-protocol-autosolver/blob/master/docs/troubleshooting.md) doc first, and if this doesn't help please create new ticket with more details about the issue.

About Ukrainian language: this is indeed missing in latest release, and will be a part of 2.10.
