### ISSUE TITLE
Breach Protocol Autosolve Bug

### ISSUE THREAD

**Issue by Arbiter1479** [marcincichocki/breach-protocol-autosolver#389]
**Describe the bug**

﻿Hello, I've been using this mod for quite a while and it worked mostly fine. However, recently I started encountering issues with the automated process. Running analyse or auto solve tells me that an error has occured while trying to gather data.

When I attempted to recalibrate, the software is able to see all the numbers correctly but still is unable to solve.

I have tried:
- Running as admin
- Checking my display setting (Ensure autobreacher is looking at the right screen)
- Recalibrating grid threshold
- Switching on and off various settings such as Extended daemons and type range ON/OFF or Automated Grid Threshold ON/OFF etc
- Using different cyberdecks

**To Reproduce**

1. Have main mission "Disasterpiece" be active
2. Go to the terminal outside of the old power plant in Charter Hill. A netrunner can be seen sitting in front of the television with the terminal on it's right
3. Attempt to jack into the terminal
4. Use autobreacher
5. Error will proc

**Expected behavior**

Autobreacher was expected to solve breach protocol.

**Software information**

- Operating System:
- _Cyberpunk 2077_ platform: Native, V2.11
- _BPA_ version: 2.12.0
- relevant _BPA_ settings: 
- Filter OCR results ON
- Automated grid threshold OFF(170)
- Automatic daemons threshold ON
- Automatic types threshold ON
- Used fixed buffer size ON
- Fixed Buffer Size 20
- Extended daemons and type range ON

**Additional files**
![Breach_Protocol_Autosolver_2024-02-18_20-28-46](https://github.com/marcincichocki/breach-protocol-autosolver/assets/14255076/4e0d94e9-def5-4c3d-89c3-061ce13014dd)
![Sun Feb 18 2024 20 23 49 GMT+0800 (Singapore Standard Time)](https://github.com/marcincichocki/breach-protocol-autosolver/assets/14255076/cdfda592-562f-4758-9112-cad8849941b2)
![Cyberpunk2077_2024-02-18_20-24-15](https://github.com/marcincichocki/breach-protocol-autosolver/assets/14255076/91e44e6c-e3c1-4f9d-a119-0ecf48e18fac)
![Cyberpunk2077_2024-02-18_20-24-25](https://github.com/marcincichocki/breach-protocol-autosolver/assets/14255076/19838715-52a5-431e-a17e-03f8be4bb419)
[bpa-snapshot-1ca78172-410e-4f49-b766-08d95beaec2e.zip](https://github.com/marcincichocki/breach-protocol-autosolver/files/14322543/bpa-snapshot-1ca78172-410e-4f49-b766-08d95beaec2e.zip)

**Comment by marcincichocki** [comment]
@Arbiter1479  Please try to set fixed threshold for daemons. 140 works for me.

As a side note, in the re-calibration screen you can click on the navigation in the header and it will show you different fragments and their validation status.
